# -*- coding: utf-8 -*-
"""Section 10B - writes Final_Report/FIGURE_INDEX.md and TABLE_INDEX.md (RE-ANALYSIS 2026).
Numbers and pages come from the LaTeX build (main.aux / main.lof / main.lot); the image provenance comes from
Figures/figure_sources.json (SHA-256 of every report image against the Section 10A manifest); the table sources are the
'Source:' notes that gen_tables.py writes under every table.
Usage: python build_indexes.py <13_Report dir> <build dir with main.aux>"""
import os, re, sys, json, glob
R, B = sys.argv[1:3]
aux = open(os.path.join(B, "main.aux"), encoding="utf-8", errors="ignore").read()
num = dict(re.findall(r"\\newlabel\{([^}]+)\}\{\{([^}]*)\}\{([^}]*)\}", aux) and
           [(a, b) for a, b, _ in re.findall(r"\\newlabel\{([^}]+)\}\{\{([^}]*)\}\{([^}]*)\}", aux)])
page = {a: c for a, b, c in re.findall(r"\\newlabel\{([^}]+)\}\{\{([^}]*)\}\{([^}]*)\}", aux)}
src = json.load(open(os.path.join(R, "Figures", "figure_sources.json"), encoding="utf-8"))
byfile = {d["file"]: d for d in src}
PROV = {"drawing": "Section 3 engineering drawing / schematic (project file)",
        "cad_render": "render of the SpaceClaim CAD export (not a GUI screenshot)",
        "mesh_render": "matplotlib render of the Fluent mesh arrays (not a GUI screenshot)",
        "cfd_plot": "matplotlib plot of exported Fluent 2026 R1 data",
        "mechanical": "ANSYS Mechanical 2026 R1 Graphics.ExportImage render, unedited",
        "data_plot": "matplotlib plot of project solver output tables",
        "analytical_plot": "matplotlib plot of the Section 2 analytical model",
        "lsdyna_plot": "matplotlib plot of the additional LS-DYNA analysis output (12C plot file, title strip cropped)"}


GREEK = {"mu": "μ", "rho": "ρ", "lambda": "λ", "sigma": "σ", "Delta": "Δ", "alpha": "α", "varepsilon": "ε", "nu": "ν",
         "omega": "ω", "le": "≤", "ge": "≥", "approx": "≈", "times": "×", "S": "§", "diameter": "Ø", "textdegree": "°", "pm": "±",
         "infty": "∞", "lambda_1": "λ1", "lamone": "λ1", "phi": "φ", "Delta T": "ΔT"}


def clean(s):
    s = re.sub(r"\\cite[pt]?\{([^}]+)\}", lambda m: "[%s]" % m.group(1), s)
    s = s.replace("\\ ", " ")
    s = re.sub(r"\\(mu|rho|lambda|sigma|Delta|alpha|varepsilon|nu|omega|leq?|geq?|approx|times|S|diameter|textdegree|pm|infty|lamone|phi)(?![a-zA-Z])\s?",
               lambda m: GREEK[m.group(1).rstrip("q")], s)
    s = re.sub(r"\\(texttt|emph|textbf|mathrm|text)\{([^{}]*)\}", r"\2", s)
    s = s.replace("\\_", "_").replace("~", " ").replace("\\,", " ").replace("\\%", "%").replace("--", "–")
    s = re.sub(r"\\lamone", "λ1", s)
    s = re.sub(r"\\ref\{([^}]+)\}", lambda m: num.get(m.group(1), "?"), s)
    s = re.sub(r"\$([^$]*)\$", r"\1", s)
    s = re.sub(r"\\[a-zA-Z]+\s?", "", s).replace("{", "").replace("}", "")
    return re.sub(r"\s+", " ", s.replace("|", "/")).strip()


def caption(block):
    i = block.rfind("\\caption")
    j = i + len("\\caption")
    if block[j] == "[":                     # short (list) caption
        d, k = 0, j
        while True:
            d += {"[": 1, "]": -1}.get(block[k], 0)
            if d == 0: break
            k += 1
        j = k + 1
    d, k = 0, j
    while True:
        d += {"{": 1, "}": -1}.get(block[k], 0)
        if d == 0: break
        k += 1
    return block[j + 1:k]


# ------------------------------------------------------------------ figures
texs = sorted(glob.glob(os.path.join(R, "Source", "chapters", "ch*.tex"))) + [os.path.join(R, "Appendices", "appendices.tex")]
rows, used = [], set()
for t in texs:
    txt = open(t, encoding="utf-8").read()
    for m in re.finditer(r"\\begin\{figure\}.*?\\end\{figure\}", txt, re.S):
        blk = m.group(0)
        lab = [l for l in re.findall(r"\\label\{([^}]+)\}", blk) if l.startswith("fig:")][-1]
        files = re.findall(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}", blk)
        used.update(files)
        rows.append((num[lab], page[lab], clean(caption(blk)), files, os.path.relpath(t, R)))
key = lambda n: [(0, int(p)) if p.isdigit() else (1, p) for p in n.split(".")]
rows.sort(key=lambda r: key(r[0]))
nimg = sum(len(r[3]) for r in rows)
allok = all(byfile[f]["source_matches_project"] for r in rows for f in r[3])
L = ["# Figure Index — Section 10B Final Report", "",
     "Generated by `Source/scripts/build_indexes.py` from the LaTeX build and `Figures/figure_sources.json`.", "",
     "- Numbered figures in the report: **%d** (containing %d image panels); cover image: `PHYSICS_SCHEMATIC.png` (also Figure 2.2)." % (len(rows), nimg),
     "- Every panel comes from a project file; its SHA-256 matches the Section 10A integrity manifest (`11_Final_Audit/Integrity/manifest_10A.csv`) or, for the Section 13 LS-DYNA panels, the 12C plot file in `15_LS_DYNA_Extension/12C_Nonlinear_Buckling/plots/`: **%s**." % ("yes, all panels" if allok else "NO — see table"),
     "- No panel is an ANSYS GUI screenshot and none was created for the report. `_nt` files are copies with the source-document title strip cropped (or blanked). In Section 11 the burned-in provenance footer was cropped from 11 report copies and the framing phrase masked in 20 (record: `Figures/figure_edits_section11.json`); no plot data, axis or label was changed.",
     "- `Figures/` holds %d prepared images; %d are used in the report, the rest were removed during trimming and are kept for the presentation phase." % (len(src), len(used)), "",
     "| Fig. | Page | Title | Panel file(s) | Project source path | SHA-256 match | Provenance | Title strip removed |",
     "|---|---|---|---|---|---|---|---|"]
for n, p, c, files, t in rows:
    ds = [byfile[f] for f in files]
    L.append("| %s | %s | %s | %s | %s | %s | %s | %s |" % (
        n, p, c, "<br>".join("`%s`" % f for f in files),
        "<br>".join("`%s`" % d["project_path"] for d in ds),
        "yes" if all(d["source_matches_project"] and d["source_sha256"] == d["manifest_sha256"] for d in ds) else "NO",
        "; ".join(sorted({PROV.get(d["provenance"], d["provenance"]) for d in ds})),
        "<br>".join("%d px" % d["title_strip_cropped_px"] if d["title_strip_cropped_px"] else "–" for d in ds)))
open(os.path.join(R, "Final_Report", "FIGURE_INDEX.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")

# ------------------------------------------------------------------ tables
idx = [l.rstrip("\n").split("\t") for l in open(os.path.join(R, "Tables", "tables_index.tsv"), encoding="utf-8")]
where = {}
for t in texs:
    for f in re.findall(r"\\input\{\.\./Tables/([^}]+)\}", open(t, encoding="utf-8").read()):
        where[f] = os.path.relpath(t, R)
trows = []
for name, lab, cap in idx:
    txt = open(os.path.join(R, "Tables", name + ".tex"), encoding="utf-8").read()
    note = re.search(r"\\parbox\{\\linewidth\}\{\\footnotesize\\raggedright (.*)\}\s*\\end\{table\}", txt, re.S)
    note = clean(note.group(1)) if note else ""
    srcn = note
    master = "yes" if "MASTER_PROJECT_DATA" in note or "master" in note.lower() else "no (section documents)"
    trows.append((num.get(lab, "?"), page.get(lab, "?"), clean(cap), name + ".tex", where.get(name, "NOT INPUT"), master, srcn))
trows.sort(key=lambda r: key(r[0]))
T = ["# Table Index — Section 10B Final Report", "",
     "Generated by `Source/scripts/build_indexes.py`. Every table is written by `Source/scripts/gen_tables.py`;",
     "result values are read by ID from `11_Final_Audit/MASTER_PROJECT_DATA.csv` (sha256 of the file used is recorded in `REPORT_QC_CHECKLIST.md`).", "",
     "- Numbered tables in the report: **%d** (%d in chapters, %d in appendices)." % (
         len(trows), sum(1 for r in trows if r[0][0].isdigit()), sum(1 for r in trows if not r[0][0].isdigit())), "",
     "| Table | Page | Title | File | Used in | Values from master dataset | Source note |", "|---|---|---|---|---|---|---|"]
for r in trows:
    T.append("| %s | %s | %s | `%s` | `%s` | %s | %s |" % r)
open(os.path.join(R, "Final_Report", "TABLE_INDEX.md"), "w", encoding="utf-8").write("\n".join(T) + "\n")
print("figures", len(rows), "panels", nimg, "all sha ok", allok, "| tables", len(trows),
      "not input", [r[3] for r in trows if r[4] == "NOT INPUT"])
