# -*- coding: utf-8 -*-
"""Section 10B - writes the report tables (13_Report/Tables/tab_*.tex).
RE-ANALYSIS 2026. Every result value in a table is read from 11_Final_Audit/MASTER_PROJECT_DATA.csv by ID
(function V). Values that are not master rows (solver settings, mesh sizing controls, property tables, detailed
section results) are written as literals with their source document named in the table note; qc_10B.py traces
every such number back to a project document. Derived percentages are computed here from master values.
Usage: python gen_tables.py <MASTER_PROJECT_DATA.csv> <9B-2 PARAMETRIC_STRUCTURAL_RESULTS.csv> <Tables dir>"""
import csv, os, sys
MCSV, PCSV, OUT = sys.argv[1:4]
with open(MCSV, encoding="utf-8") as fh:
    fh.readline()
    M = {r["ID"]: r for r in csv.DictReader(fh)}
with open(PCSV, encoding="utf-8") as fh:
    fh.readline()
    P = {r["Case"]: r for r in csv.DictReader(fh)}


def V(i):
    return M[i]["Value"]


def F(i):
    return float(M[i]["Value"])


def neg(s):
    s = str(s)
    return "$-$" + s[1:] if s.startswith("-") else s


def g(x):
    """thousands separator for integers / integer part"""
    s = str(x)
    sign = ""
    if s.startswith("-"):
        sign, s = "-", s[1:]
    if "." in s:
        a, b = s.split(".")
        return neg(sign + "{:,}".format(int(a)) + "." + b)
    return neg(sign + "{:,}".format(int(s)))


def pct(a, b, nd=1):
    return neg("%+.*f\\,\\%%" % (nd, (a - b) / b * 100))


def sci(s, unit=""):
    m, e = ("%.1e" % float(s)).split("e")
    return "$%s\\times10^{%d}$%s" % (m, int(e), unit)


TABLES = []


def table(name, caption, label, colspec, header, rows, note, size="\\small", wide=False, pos="htbp"):
    lines = ["%% generated by gen_tables.py - RE-ANALYSIS 2026", "\\begin{table}[%s]" % pos, "\\centering", size,
             "\\caption{%s}" % caption, "\\label{%s}" % label]
    env = "tabularx" if wide else "tabular"
    lines.append("\\begin{%s}%s{%s}" % (env, "{\\linewidth}" if wide else "", colspec))
    lines.append("\\toprule")
    lines.append(" & ".join(header) + " \\\\")
    lines.append("\\midrule")
    for r in rows:
        if r == "MID":
            lines.append("\\midrule")
        else:
            lines.append(" & ".join(str(c) for c in r) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{%s}" % env)
    if note:
        lines.append("\\par\\smallskip\\parbox{\\linewidth}{\\footnotesize\\raggedright %s}" % note)
    lines.append("\\end{table}")
    open(os.path.join(OUT, name + ".tex"), "w", encoding="utf-8").write("\n".join(lines) + "\n")
    TABLES.append((name, label, caption))


MD = "\\texttt{MASTER\\_PROJECT\\_DATA.csv}"
L = "\\raggedright\\arraybackslash"

# ------------------------------------------------------------------------------------------------ Chapter 2 / 4
table("tab_geometry", "Duct geometry of the baseline (selected class-B inputs, verified in the CAD model)", "tab:geometry",
      ">{%s}p{0.42\\linewidth}lrl" % L, ["Parameter", "Symbol", "Value", "Unit"],
      [["Inner (bore) diameter", "$D_i$", V("M023"), "mm"], ["Outer diameter", "$D_o$", V("M024"), "mm"], ["Wall thickness", "$t$", V("M025"), "mm"],
       ["Length", "$L$", V("M026"), "mm"], ["Hydraulic diameter", "$D_h$", V("M027"), "mm"], ["Slenderness of the flow passage", "$L/D_i$", "30", "--"],
       ["Diameter ratio", "$D_o/D_i$", "2", "--"], ["Fluid flow area", "$A_c$", V("M028"), "mm$^2$"],
       ["Solid volume", "$V_s$", "$5.654867\\times10^{-4}$", "m$^3$"], ["Heated outer area, true cylinder", "$A_o$", V("M030"), "m$^2$"],
       ["Heated outer area, CFD 48-facet polygon", "$A_{o,48}$", V("M031"), "m$^2$"]],
      "Source: %s rows M023--M031 (CAD values from \\texttt{cad\\_measurements.json}; the 48-facet area from the Fluent surface-integral report). Status VERIFIED." % MD)

table("tab_operating", "Baseline operating condition P00 (selected inputs)", "tab:operating", ">{%s}p{0.45\\linewidth}rl>{%s}p{0.25\\linewidth}" % (L, L),
      ["Quantity", "Value", "Unit", "Status"],
      [["Fluid", "air", "--", "selected"], ["Inlet temperature $T_{in}$", V("M002"), "K", "selected"],
       ["Inlet velocity $V_{in}$ (uniform)", V("M003"), "m/s", "selected"], ["Inlet turbulence intensity", "4.411", "\\%", "assumed (A-020b)"],
       ["Outlet static pressure (gauge)", "0", "Pa", "selected"], ["Operating pressure $p_{op}$", "101,325", "Pa", "selected"],
       ["Outer-wall heat flux $q''$ (uniform)", "8000", "W/m$^2$", "selected"], ["Equivalent bore flux $q''D_o/D_i$", "16,000", "W/m$^2$", "calculated"],
       ["End faces", "adiabatic", "--", "assumed (A-011)"], ["Inlet Reynolds number (CFD)", g(V("M034")), "--", "simulated"]],
      "Source: %s rows M002--M006 and M034; \\texttt{baseline\\_parameters.json}." % MD)

table("tab_air", "Air properties used by the analytical model (at the inlet and outlet bulk temperatures)", "tab:air", "lrrl",
      ["Property", "300 K", "368.9 K", "Unit"],
      [["Density $\\rho = p_{op}/(RT)$", "1.1766", "0.9569", "kg/m$^3$"], ["Specific heat $c_p$", "1007", "1011", "J/(kg\\,K)"],
       ["Dynamic viscosity $\\mu$", "$1.846\\times10^{-5}$", "$2.176\\times10^{-5}$", "Pa\\,s"], ["Thermal conductivity $k$", "0.02624", "0.03123", "W/(m\\,K)"],
       ["Prandtl number $Pr$", "0.707", "0.696", "--"]],
      "Source: \\texttt{02\\_Engineering\\_Calculations/MATERIAL\\_PROPERTIES.md}; $c_p$, $\\mu$, $k$, $Pr$ from Incropera et al.\\ Table A.4 \\cite{incropera}; "
      "density computed from the ideal-gas law at 101,325~Pa with $R = 287.058$~J/(kg\\,K) because tabulated densities refer to 100~kPa. "
      "In Fluent, $c_p$, $\\mu$ and $k$ are piecewise-linear over 8 points between 250 and 600~K.")

table("tab_inconel", "Inconel 718 (age-hardened) properties as a function of temperature", "tab:inconel", "lrrrrr",
      ["Property", "20\\,\\textdegree C", "100\\,\\textdegree C", "200\\,\\textdegree C", "300\\,\\textdegree C", "400\\,\\textdegree C"],
      [["Young's modulus $E$ [GPa]", "204", "199", "193", "187", "180"], ["Thermal conductivity $k_s$ [W/(m\\,K)]", "11.5", "12.1", "13.5", "15.2", "17.1"],
       ["Specific heat $c_{p,s}$ [J/(kg\\,K)]", "460", "458", "468", "485", "501"], ["0.2\\,\\% proof strength $S_y$ [MPa]", "1030", "1060", "1040", "1020", "1000"],
       "MID",
       ["\\multicolumn{6}{@{}l}{Mean CTE from 21\\,\\textdegree C: 12.8 / 13.3 / 13.9 / 14.2 / 14.8 $\\times10^{-6}$/K for means to 93 / 204 / 316 / 427 / 538\\,\\textdegree C}"],
       ["\\multicolumn{6}{@{}l}{Density $\\rho_s$ = 8190 kg/m$^3$ (constant); Poisson's ratio $\\nu$ = 0.294 [ASSUMED], literature range 0.284--0.294}"]],
      "Sources: VDM Alloy 718 Data Sheet No.~4127 \\cite{vdm718} ($E$, $k_s$, $c_{p,s}$, $S_y$); High Temp Metals / Special Metals technical data \\cite{htm718} "
      "(mean CTE, density). Poisson's ratio is in neither datasheet and is an assumption (A-021). $S_y$ values are typical, not minimum-guaranteed (A-022). "
      "In Mechanical the secant CTE is re-referenced from its 70\\,\\textdegree F datum to $T_{ref} = 300$~K (MPAMOD).")

table("tab_bc", "CFD boundary conditions (read back from Fluent and verified)", "tab:bc", ">{%s}p{0.30\\linewidth}>{%s}p{0.22\\linewidth}>{%s}p{0.38\\linewidth}" % (L, L, L),
      ["Zone", "Type", "Value"],
      [["\\texttt{fluid\\_inlet}", "velocity inlet", "23.5 m/s normal; 300 K; $I = 4.411$\\,\\%, $D_h = 0.020$~m"],
       ["\\texttt{fluid\\_outlet}", "pressure outlet", "0 Pa gauge; backflow 300 K; reverse flow prevented"],
       ["\\texttt{fluid\\_solid\\_interface} (+ shadow)", "wall, coupled", "no-slip; temperature and heat flux solved, never imposed"],
       ["\\texttt{heated\\_outer\\_wall}", "wall, heat flux", "8000 W/m$^2$ (the only heat input)"],
       ["\\texttt{solid\\_inlet\\_end}, \\texttt{solid\\_outlet\\_end}", "wall, heat flux", "0 W/m$^2$ (adiabatic)"]],
      "Source: \\texttt{06\\_Fluent\\_CFD/FLUENT\\_SETUP\\_NOTES.md} \\S8. A heat-path audit confirmed that the flux is applied exactly once.")

table("tab_supports", "Structural load cases and support scenarios (idealised boundary conditions)", "tab:supports",
      ">{%s}p{0.20\\linewidth}>{%s}p{0.52\\linewidth}>{%s}p{0.18\\linewidth}" % (L, L, L), ["Case", "Constraint definition", "Role"],
      [["LC1 free expansion", "3 outer-ring nodes on the inlet face ($\\theta$ = 0/120/240\\textdegree), $U_\\theta = U_z = 0$ in the duct cylindrical system; statically determinate", "gradient stress only"],
       ["LC2 = S1", "$U_z = 0$ on both complete end faces; $U_\\theta = 0$ at 3 mid-span outer nodes; radial free; ends free to sway, end rotation held (guided column, $K = 1$)", "official baseline"],
       ["S2", "$U_z = U_\\theta = 0$ on every node of both end faces (clamped--clamped, $K = 0.5$)", "sensitivity"],
       ["S3", "inlet face $U_z = U_\\theta = 0$ (clamped); outlet on a deformable remote point on the axis, $U = 0$, rotations free (pinned, $K = 0.699$)", "sensitivity"]],
      "Source: %s rows M019--M022. None of these represents a defined real flange; the real end restraint is undefined (open task T-034)." % MD)

table("tab_assumptions", "Principal modelling assumptions and their final status", "tab:assumptions",
      "l>{%s}p{0.42\\linewidth}>{%s}p{0.14\\linewidth}>{%s}p{0.25\\linewidth}" % (L, L, L), ["ID", "Assumption", "Status", "Evidence"],
      [["A-004", "steady state", "valid", "time-invariant boundary conditions"], ["A-005", "incompressible ideal gas", "valid", "$\\Delta p$ 0.43\\,\\% of $p_{op}$; Mach $\\le$ 0.097"],
       ["A-007", "buoyancy neglected", "valid", "$Ri = 4.4\\times10^{-5}$"], ["A-008", "viscous dissipation neglected", "valid", "$Br = 1.8\\times10^{-3}$"],
       ["A-009", "one-way thermal $\\rightarrow$ structural coupling", "valid", "flow-area change 0.70\\,\\%"],
       ["A-010", "uniform outer-wall heat flux", "assumed", "idealisation"], ["A-011", "adiabatic end faces", "assumed", "idealisation"],
       ["A-012", "linear elastic material", "valid for statics", "utilisation $\\le$ 0.645 in all cases"], ["A-014", "hydraulically smooth wall", "assumed", "not tested"],
       ["A-015", "internal radiation neglected", "assumed / open", "not tested (T-009)"], ["A-016", "stress-free temperature 300 K", "valid", "TREF in every solver input"],
       ["A-020b", "inlet turbulence intensity 4.411\\,\\%", "assumed", "influence limited to the first diameters"],
       ["A-021", "Poisson's ratio 0.294", "assumed", "in neither datasheet"], ["A-022", "$S_y(T)$ typical datasheet values", "assumed", "not minimum-guaranteed"],
       ["A-024", "idealised supports S1/S2/S3", "assumed / open", "real restraint undefined (T-034)"],
       ["A-025", "perfectly straight tube, no imperfection", "assumed", "linear eigenvalue buckling (T-035)"],
       ["A-026", "linear elastic buckling", "assumed", "no stress--strain data (T-036)"]],
      "Source: \\texttt{11\\_Final\\_Audit/MASTER\\_ASSUMPTIONS.md} \\S3 (full register A-001 to A-031).", size="\\footnotesize")

table("tab_validity", "Validity ranges of property data and correlations compared with the solved ranges", "tab:validity",
      ">{%s}p{0.30\\linewidth}>{%s}p{0.26\\linewidth}>{%s}p{0.34\\linewidth}" % (L, L, L), ["Data / correlation", "Validity range", "Range reached in this project"],
      [["Air $c_p$, $\\mu$, $k$ table", "250--600 K", "baseline fluid 300.0--553.4 K; highest air-side temperature 583.4 K (Q03)"],
       ["Inconel $k_s$, $c_{p,s}$ table", "293--673 K", "baseline solid 423.97--562.13 K (cell centres); highest 591.13 K (Q03)"],
       ["Inconel $E$, $S_y$ table", "20--400\\,\\textdegree C", "mapped field 150.69--289.41\\,\\textdegree C; highest 318.0\\,\\textdegree C (Q03)"],
       ["Petukhov friction factor", "$3\\times10^3 < Re < 5\\times10^6$", "$Re$ = 25,545--32,954"],
       ["Gnielinski Nusselt number", "$3\\times10^3 < Re < 5\\times10^6$, $0.5 < Pr < 2000$", "inside"],
       ["Dittus--Boelter Nusselt number", "$Re > 10^4$, small wall-to-bulk $\\Delta T$", "wall-to-bulk $\\Delta T$ up to 206 K: outside, used only as an upper reference"]],
      "Sources: \\texttt{MATERIAL\\_PROPERTIES.md}, \\texttt{CFD\\_BASELINE\\_RESULTS.md} \\S8, \\texttt{PROJECT\\_STATE.md} \\S18.5 and \\S19.6. No property was extrapolated in any solved case.",
      size="\\footnotesize")

# ------------------------------------------------------------------------------------------------ Chapter 5
table("tab_namedsel", "Named selections created in SpaceClaim and carried into Fluent and Mechanical", "tab:namedsel",
      "l>{%s}p{0.30\\linewidth}>{%s}p{0.32\\linewidth}" % (L, L), ["Name", "Entity", "Use"],
      [["\\texttt{FLUID\\_DOMAIN}", "body: air passage", "Fluent fluid cell zone"], ["\\texttt{SOLID\\_DOMAIN}", "body: Inconel 718 annulus", "Fluent solid zone; Mechanical body"],
       ["\\texttt{FLUID\\_INLET}", "\\O{}20 disc at $z = 0$", "velocity inlet"], ["\\texttt{FLUID\\_OUTLET}", "\\O{}20 disc at $z = 600$ mm", "pressure outlet"],
       ["\\texttt{FLUID\\_WALL}", "\\O{}20 cylinder, fluid side", "near-wall grading, $y^+$ monitoring"],
       ["\\texttt{FLUID\\_SOLID\\_INTERFACE}", "both sides of the \\O{}20 surface", "conjugate coupling"],
       ["\\texttt{SOLID\\_INNER\\_INTERFACE}", "\\O{}20 cylinder, solid side", "conjugate coupling"], ["\\texttt{HEATED\\_OUTER\\_WALL}", "\\O{}40 cylinder", "heat flux 8000 W/m$^2$"],
       ["\\texttt{SOLID\\_INLET\\_END}", "annulus at $z = 0$", "adiabatic"], ["\\texttt{SOLID\\_OUTLET\\_END}", "annulus at $z = 600$ mm", "adiabatic"],
       ["\\texttt{STRUCTURAL\\_SUPPORT}", "annulus at $z = 0$", "structural restraint face"]],
      "Source: \\texttt{03\\_CAD\\_Geometry/CAD\\_NOTES.md} \\S6. All 11 selections survived the transfer to Workbench Meshing without re-creation.", size="\\footnotesize")

table("tab_geomver", "Geometry verification: analytical values against the SpaceClaim model", "tab:geomver", "lrrl",
      ["Quantity", "Analytical", "CAD", "Relative difference"],
      [["Fluid cross-sectional area [mm$^2$]", "314.1592654", "314.1592654", "$1.8\\times10^{-14}$\\,\\%"],
       ["\\texttt{FLUID\\_DOMAIN} volume [m$^3$]", "$1.884955592\\times10^{-4}$", "$1.884955592\\times10^{-4}$", "$1.4\\times10^{-14}$\\,\\%"],
       ["\\texttt{SOLID\\_DOMAIN} volume [m$^3$]", "$5.654866776\\times10^{-4}$", "$5.654866776\\times10^{-4}$", "0"],
       ["\\texttt{HEATED\\_OUTER\\_WALL} area [m$^2$]", "0.07539822369", "0.07539822369", "0"],
       ["Interface area, fluid side = solid side [m$^2$]", "0.03769911184", "0.03769911184", "0 (identical to 17 digits)"],
       ["Fluid + solid volume [m$^3$]", "\\multicolumn{3}{l}{$7.539822369\\times10^{-4}$ = full \\O{}40 $\\times$ 600 mm cylinder (no gap, no overlap)}"]],
      "Source: \\texttt{03\\_CAD\\_Geometry/CAD\\_NOTES.md} \\S5 and \\S7; raw values in \\texttt{Geometry\\_Check/cad\\_measurements.json}.", size="\\footnotesize")

# ------------------------------------------------------------------------------------------------ Chapter 6
table("tab_solver", "Fluent solver and physical-model settings of the baseline solution", "tab:solver", ">{%s}p{0.30\\linewidth}>{%s}p{0.60\\linewidth}" % (L, L),
      ["Setting", "Value"],
      [["Software", "ANSYS Fluent 2026 R1 (Student licence, 4-way parallel)"], ["Solver", "pressure-based, coupled pressure--velocity, steady, absolute velocity"],
       ["Energy equation", "on (fluid and solid)"], ["Turbulence model", "$k$--$\\omega$ SST, blended wall treatment (\\texttt{correlation} $\\omega$ wall treatment)"],
       ["Gravity / radiation", "off / off"], ["Air", "incompressible ideal gas, $\\rho = p_{op}/(RT)$; $c_p$, $\\mu$, $k$ piecewise-linear, 250--600 K"],
       ["Inconel 718", "$\\rho$ = 8190 kg/m$^3$; $k_s$, $c_{p,s}$ piecewise-linear, 293--673 K"], ["Gradient", "least-squares cell-based"],
       ["Initialisation", "standard: 300 K, $w$ = 23.5 m/s, 0 Pa gauge in the whole domain (cold start)"]],
      "Source: \\texttt{06\\_Fluent\\_CFD/FLUENT\\_SETUP\\_NOTES.md} \\S5--\\S10 and \\texttt{Baseline/CFD\\_BASELINE\\_RESULTS.md} \\S2.")

table("tab_stages", "Solution staging and discretisation of the baseline run", "tab:stages", "lllp{0.35\\linewidth}",
      ["Stage", "Iterations", "Schemes", "Purpose"],
      [["1", "1--150", "first-order upwind, energy off", "develop velocity and turbulence fields"], ["2", "151--300", "first-order upwind, energy on", "bring up the thermal field"],
       ["3", "301--600", "second-order (pressure, momentum, $k$, $\\omega$, energy)", "production discretisation; convergence checked every 100 iterations"],
       ["confirm", "601--700", "second-order", "confirm that the converged state holds"]],
      "Source: \\texttt{CFD\\_BASELINE\\_RESULTS.md} \\S3. Wall clock 12 min 58 s on 4 cores for 700 iterations, including audits and exports.", size="\\footnotesize")

table("tab_convcrit", "Convergence criteria and final state of the baseline solution (iteration 700)", "tab:convcrit", "lll",
      ["Criterion", "Target", "Achieved"],
      [["Continuity residual", "$< 10^{-4}$", "$9.0\\times10^{-11}$"], ["Momentum residuals", "$< 10^{-4}$", "$\\le 1.6\\times10^{-14}$"],
       ["$k$ / $\\omega$ residuals", "$< 10^{-4}$", "$7.2\\times10^{-13}$ / $2.0\\times10^{-13}$"], ["Energy residual", "$< 10^{-6}$", "$1.6\\times10^{-14}$"],
       ["$T_{out}$ drift over the last 200 iterations", "$< 0.1$ K", "$2.3\\times10^{-6}$ K"], ["$\\Delta p$ relative drift", "$< 0.1$\\,\\%", "$6.9\\times10^{-8}$\\,\\%"],
       ["Interface heat-rate relative drift", "$< 0.1$\\,\\%", "$3.5\\times10^{-7}$\\,\\%"], ["Mass imbalance", "$< 0.01$\\,\\%", "$7.0\\times10^{-13}$\\,\\%"],
       ["Energy imbalance", "$< 0.5$\\,\\%", "$3.1\\times10^{-11}$\\,\\%"]],
      "Source: \\texttt{CFD\\_BASELINE\\_RESULTS.md} \\S3; imbalances also %s rows M047--M048 (VERIFIED)." % MD, size="\\footnotesize")

# ------------------------------------------------------------------------------------------------ Chapter 7
table("tab_meshfam", "CFD mesh family: sizing controls (same topology on all levels)", "tab:meshfam", "lrrr",
      ["Control", "Coarse", "Medium", "Fine"],
      [["Core divisions per side $N_C$", "8", "12", "18"], ["Circumferential divisions $N_\\theta = 4N_C$", "32", "48", "72"],
       ["Fluid radial layers", "18", "24", "32"], ["Solid radial layers", "7", "10", "15"], ["Axial divisions", "60", "90", "135"],
       ["Axial cell length [mm]", "10.000", "6.667", "4.444"], ["First fluid cell height [\\textmu m]", "12.2", "12.2", "12.2"],
       ["Fluid growth rate", "1.3182", "1.2091", "1.1385"], ["Solid first cell at the interface [mm]", "0.5", "0.5", "0.5"]],
      "Source: \\texttt{05\\_Meshing/MESH\\_NOTES.md} \\S3--\\S4. Linear refinement ratio $r \\approx 1.46$ between levels.", size="\\footnotesize")

table("tab_meshq", "CFD mesh statistics and quality (Fluent \\texttt{mesh/check} and \\texttt{mesh/quality})", "tab:meshq", "lrrr",
      ["Quantity", "Coarse", "Medium (baseline)", "Fine (reference)"],
      [["Total cells", g(V("M058")), g(V("M033")), g(V("M050"))], ["Fluid / solid cells", "38,400 / 13,440", "116,640 / 43,200", "354,780 / 145,800"],
       ["Conformal interface faces", "1,920", "4,320", "9,720"], ["Cell type", "100\\,\\% hexahedra", "100\\,\\% hexahedra", "100\\,\\% hexahedra"],
       ["Minimum orthogonal quality", "0.4482", "0.4458", "0.3144"], ["Maximum skewness", "0.6564", "0.7600", "0.8364"],
       ["Maximum aspect ratio", "974.5", "654.4", "437.9"], ["Negative-volume cells", "0", "0", "0"]],
      "Source: \\texttt{05\\_Meshing/MESH\\_NOTES.md} \\S5--\\S6 and \\texttt{Mesh\\_Quality/MESH\\_QUALITY\\_TABLE.md}; cell totals %s rows M033, M050, M058." % MD, size="\\footnotesize")

# ------------------------------------------------------------------------------------------------ Chapter 8
table("tab_cfdres", "Baseline CFD results (medium mesh, converged, official baseline P00)", "tab:cfdres", ">{%s}p{0.50\\linewidth}rl" % L,
      ["Quantity", "Value", "Unit"],
      [["Cells (fluid + solid)", g(V("M033")), "--"], ["Reynolds number, inlet / outlet", g(V("M034")) + " / " + g(V("M035")), "--"],
       ["Pressure drop (area-weighted static, inlet $-$ outlet)", V("M036"), "Pa"], ["Outlet bulk temperature (mass-weighted)", V("M037"), "K"],
       ["Heat-transfer rate through the heated wall", V("M038"), "W"], ["Maximum solid temperature (outer-wall facet)", V("M039"), "K"],
       ["Maximum solid temperature (hottest cell centre)", V("M040"), "K"], ["Through-wall $\\Delta T$ at mid-span ($z$ = 300 mm)", V("M041"), "K"],
       ["Fully developed Nusselt number ($x/D$ 18--29)", V("M042"), "--"], ["Fully developed Darcy friction factor ($x/D$ 18--29)", V("M043"), "--"],
       ["$y^+$ minimum / area mean / maximum", "%s / %s / %s" % (V("M044"), V("M045"), V("M046")), "--"],
       ["Mass imbalance / energy imbalance", "%s / %s" % (sci(V("M047")), sci(V("M048"))), "\\%"]],
      "Source: %s rows M033--M048 (VERIFIED from the Fluent flux and surface-integral reports, except M035 REPORTED and M041--M043 CROSS-CHECKED). "
      "$Q$ = 602.755~W is 8000~W/m$^2$ times the inscribed 48-gon area; the same flux on the true cylinder is 603.186~W." % MD)

table("tab_anvscfd", "Section 2 analytical estimates compared with the baseline CFD (different modelling levels)", "tab:anvscfd",
      ">{%s}p{0.25\\linewidth}rrr>{%s}p{0.30\\linewidth}" % (L, L), ["Quantity", "Analytical", "CFD medium", "Difference", "Explanation"],
      [["$Q$ [W]", V("M071"), V("M038"), pct(F("M038"), F("M071"), 3), "exactly the 48-gon lateral-area ratio"],
       ["$T_{out}$ [K]", V("M072"), V("M037"), "+0.08 K", "faceting of the CFD section"],
       ["$\\Delta p$ [Pa]", V("M073"), V("M036"), pct(F("M036"), F("M073"), 2), "friction 7.7\\,\\% lower, profile-development term higher; partly compensating"],
       ["$T_{max}$ solid [K]", V("M074"), V("M039"), "$-$19.1 K", "higher CFD film coefficient ($-$15.0 K) and axial conduction ($-$4.2 K)"],
       ["$\\Delta T_{wall}$ [K]", V("M075") + " (exit)", "7.361 ($z$ = 570 mm)", "+1.0\\,\\%", "1-D conduction confirmed away from the ends"],
       ["$Nu_{fd}$", "49.6", V("M042"), "+9.3\\,\\%", "CFD implies property exponent $n \\approx 0.36$ instead of 0.5"],
       ["$f_{fd}$", "0.0241", V("M043"), "$-$10.4\\,\\%", "gas-heating (variable-property) effect, F-029"]],
      "Sources: %s rows M036--M043 and M071--M075; explanations from \\texttt{CFD\\_VS\\_ANALYTICAL.md} and \\texttt{PROJECT\\_STATE.md} \\S5b. "
      "Neither level was adjusted to match the other." % MD, size="\\footnotesize")

# ------------------------------------------------------------------------------------------------ Chapter 9
table("tab_mi", "CFD mesh-independence study: three meshes and Richardson extrapolation", "tab:mi", "lrrrrl",
      ["Quantity", "Coarse", "Medium", "Fine", "Extrapolated", "Status"],
      [["Cells", g(V("M058")), g(V("M033")), g(V("M050")), "--", "--"], ["$\\Delta p$ [Pa]", V("M059"), V("M036"), V("M051"), V("M070") + "$^a$", "B"],
       ["$T_{out}$ [K]", V("M060"), V("M037"), V("M052"), "--", "D (geometry)"], ["$Q$ [W]", V("M061"), V("M038"), V("M053"), "603.186$^b$", "D (geometry)"],
       ["$T_{max}$ solid [K]", V("M062"), V("M039"), V("M054"), V("M066"), "B"], ["$\\Delta T_{wall}$ mid-span [K]", V("M063"), V("M041"), V("M055"), V("M067"), "B"],
       ["$Nu_{fd}$", V("M064").split(" / ")[0], V("M042"), V("M056").split(" / ")[0], V("M068"), "B"],
       ["$f_{fd}$", V("M064").split(" / ")[1], V("M043"), V("M056").split(" / ")[1], V("M069"), "B"],
       ["$y^+$ maximum", V("M065"), V("M046"), V("M057"), "--", "B / E"]],
      "Source: %s rows M033--M070. Status: B approximately convergent; D affected by the polygon geometry; E inconclusive (sampling position). "
      "$^a$ geometry-adjusted estimate. $^b$ exact circle value recovered by extrapolating the raw values (check of the procedure)." % MD, size="\\footnotesize")

table("tab_gci", "Convergence indicators (Celik et al.\\ procedure, $r_{21}$ = 1.4631, $r_{32}$ = 1.4555)", "tab:gci", "lrrrr",
      ["Quantity", "Ratio $R$", "Apparent order $p$", "Extrapolated", "GCI$_{fine}$"],
      [["$\\Delta p$, geometry-adjusted", "0.68", "1.05", "441.8 Pa", "0.89\\,\\% (3.9 Pa)"], ["$T_{max}$ solid", "0.62", "1.31", "558.1 K", "3.4 K (1.3\\,\\% of rise)"],
       ["$\\Delta T_{wall}$ mid-span", "0.60", "1.37", "7.620 K", "0.029 K"], ["$Nu_{fd}$", "0.62", "1.30", "55.43", "1.8\\,\\%"], ["$f_{fd}$", "0.64", "1.23", "0.02212", "1.8\\,\\%"]],
      "Source: \\texttt{PROJECT\\_STATE.md} \\S12.4 and \\texttt{09\\_Mesh\\_Independence/Mesh\\_Independence\\_Report.md} \\cite{celik2008}. "
      "Convergence is monotonic but the apparent order is below the formal value of 2.", size="\\footnotesize")

# ------------------------------------------------------------------------------------------------ Chapter 10
table("tab_mapping", "Numerical checks of the CFD-to-Mechanical temperature transfer (Section 7A)", "tab:mapping", ">{%s}p{0.42\\linewidth}>{%s}p{0.48\\linewidth}" % (L, L),
      ["Check", "Result"],
      [["Source field", "converged medium solution; Fluent node temperatures 423.84--562.54 K (48,048 nodes)"],
       ["Coverage", "108,252 / 108,252 structural nodes mapped; 0 unmapped"], ["Mapped range", "423.84--562.56 K (identical in LC1 and LC2)"],
       ["Error (A) against exact shape-function evaluation", "maximum 0.081 K inside the source mesh; mean 0.002 K"],
       ["Error (B) against independent finite-volume reference", "maximum 2.57 K at the bore within $\\sim$11 mm of the inlet; $\\le$ 0.25 K over $z$ = 14--586 mm; mean 0.039 K"],
       ["Mid-span through-wall $\\Delta T$", "mapped 7.580 K against Fluent 7.581 K"], ["Volume-mean temperature", "mapped 525.520 K against Fluent 525.483 K"],
       ["Parametric cases (9B-2)", "all 7 cases passed; error (A) 0.086--0.154 K"]],
      "Source: \\texttt{07\\_Thermal\\_Analysis/THERMAL\\_MAPPING\\_NOTES.md}, \\texttt{CFD\\_TO\\_MECHANICAL\\_MAPPING\\_AUDIT.md}, \\texttt{PROJECT\\_STATE.md} \\S13.1 and \\S19.2.", size="\\footnotesize")

# ------------------------------------------------------------------------------------------------ Chapter 11
table("tab_smodel", "Structural model of the baseline (Section 7B)", "tab:smodel", ">{%s}p{0.30\\linewidth}>{%s}p{0.60\\linewidth}" % (L, L),
      ["Item", "Setting"],
      [["Software", "ANSYS Mechanical / MAPDL 2026 R1 (Student licence, measured limit 128,000 nodes)"],
       ["Mesh B", "SOLID186 quadratic hexahedra, 36 circumferential $\\times$ 5 through-wall $\\times$ 130 axial (bias 4, 2.13 $\\rightarrow$ 8.51 mm); %s nodes / %s elements" % (g(V("M081")), g(V("M082")))],
       ["Element quality", "minimum 0.237 (average 0.688); aspect ratio $\\le$ 4.88; Jacobian ratio $\\le$ 1.205"],
       ["Thermal load", "mapped CFD solid temperature on every node; $\\Delta T = T(x,y,z) - T_{ref}$"], ["Reference temperature", "%s K" % V("M083")],
       ["Material", "$E(T)$, secant $\\alpha(T)$, $\\nu$ = 0.294 [ASSUMED]; $S_y(T)$ used only for assessment"],
       ["Analysis", "linear static, small deflection, sparse direct solver"], ["Load cases", "LC1 (free expansion), LC2 (axially restrained, S1), LC2P (LC2 + 443.41 Pa bore pressure)"]],
      "Source: %s rows M081--M083; \\texttt{PROJECT\\_STATE.md} \\S13.1 and \\S14.1." % MD, size="\\footnotesize")

table("tab_lcres", "Static structural results of the baseline (mesh B)", "tab:lcres", ">{%s}p{0.42\\linewidth}rr" % L,
      ["Quantity", "LC1 free expansion", "LC2 restrained (S1)"],
      [["Maximum total deformation [mm]", V("M084"), V("M089")], ["Free axial growth $\\Delta L$ [mm]", V("M085"), "--"],
       ["Maximum von Mises stress [MPa]", V("M086"), V("M090")], ["Location of the maximum", "bore, $z$ = 6.5 mm", "outer edge of the inlet face"],
       ["Temperature at the maximum [K]", V("M087"), V("M093")], ["Mid-span bore von Mises [MPa]", "18.20", "--"],
       ["Axial end reaction [N]", "$\\approx 0$ (%s)" % sci(V("M088")), g(V("M091"))], ["Mean axial stress [MPa]", "$\\approx 0$", neg(V("M092"))],
       ["Pressure effect LC2P $-$ LC2 on the peak [Pa]", "--", "+" + V("M097")]],
      "Source: %s rows M084--M097 (VERIFIED from the MAPDL nodal and reaction tables)." % MD, size="\\footnotesize")

table("tab_yield", "First-yield assessment of the LC2 static state (not a structural margin; see Chapter~\\ref{ch:buckling})", "tab:yield", ">{%s}p{0.55\\linewidth}r" % L,
      ["Quantity", "Value"],
      [["Critical node temperature [K]", V("M093")], ["Local yield strength $S_y(T)$ at the critical node [MPa]", V("M094")],
       ["Yield utilisation $\\sigma_{vM}/S_y(T)$", V("M095")], ["First-yield load factor (1/utilisation)", V("M096")],
       ["First-yield margin $S_y/\\sigma_{vM} - 1$", "0.730"], ["LC1 utilisation", "0.023"]],
      "Source: %s rows M093--M096; \\texttt{STRUCTURAL\\_RESULTS.md}. $S_y(T)$ interpolated linearly in the VDM table at the node temperature; "
      "the Engineering Data scalar of 1020~MPa is a lower bound and is not used." % MD, size="\\footnotesize")

# ------------------------------------------------------------------------------------------------ Chapter 12
table("tab_smesh", "Structural mesh variants and governing results (Section 8B)", "tab:smesh", "llrrr",
      ["Mesh", "Divisions (circ.\\ $\\times$ wall $\\times$ axial, bias)", "Nodes", "LC2 max VM [MPa]", "$\\lambda_1$"],
      [["XC", "21 $\\times$ 3 $\\times$ 76, 4", "24,171", V("M111"), V("M112")], ["C", "27 $\\times$ 4 $\\times$ 98, 4", "50,652", V("M113"), V("M114")],
       ["\\textbf{B (baseline)}", "36 $\\times$ 5 $\\times$ 130, 4", "108,252", V("M115"), V("M116")], ["FR (wall)", "36 $\\times$ 6 $\\times$ 130, 4", "127,080", V("M117"), V("M118")],
       ["FA (axial)", "36 $\\times$ 5 $\\times$ 152, 4", "126,468", V("M119"), V("M120")], ["FC (circ.)", "42 $\\times$ 5 $\\times$ 130, 4", "126,294", V("M121"), V("M122")],
       ["IL (inlet bias)", "36 $\\times$ 5 $\\times$ 130, 8", "108,252", V("M123"), "--"]],
      "Source: %s rows M111--M124; node counts \\texttt{PROJECT\\_STATE.md} \\S16.1. Largest change against mesh B: 4.9$\\times10^{-4}$ (LC2 peak, XC) and "
      "5.4$\\times10^{-5}$ ($\\lambda_1$)." % MD, size="\\footnotesize")

# ------------------------------------------------------------------------------------------------ Chapter 13
table("tab_section", "Column properties and hand estimates of the buckling load factor (Section 8A)", "tab:section", "lrrr",
      ["End condition", "$KL/r$", "Euler, $E(z)$", "Euler + shear"],
      [["Guided (rotation fixed, sway free) = S1", "53.7", "1.119", "1.104"], ["Pinned--pinned", "53.7", "1.114", "1.099"],
       ["Fixed--pinned", "37.5", "2.29", "2.22"], ["Fixed--fixed (no sway)", "26.8", "4.47", "4.23"], "MID",
       ["\\multicolumn{4}{l}{$A$ = 942.48 mm$^2$; $I$ = 117,810 mm$^4$; $r$ = 11.18 mm; $L/r$ = 53.67; $C_c$ = 60.2; Johnson (guided) 1.058; squash 1.755}"]],
      "Source: \\texttt{08\\_Structural\\_Analysis/Buckling/BUCKLING\\_RESULTS.md} and \\texttt{PROJECT\\_STATE.md} \\S15.1. Load factor = $P_{cr}/N$ with "
      "$N$ = 548,936.6 N. The shear correction uses the Engesser form with Cowper's coefficient $k$ = 0.620 \\cite{cowper1966}.", size="\\footnotesize")

table("tab_buckling", "Linear eigenvalue buckling results of the baseline under S1 (Section 8A)", "tab:buckling", ">{%s}p{0.45\\linewidth}r" % L,
      ["Quantity", "Value"],
      [["Applied axial compression $N$ (LC2 end reaction) [N]", g(V("M091"))], ["$\\lambda_1 = \\lambda_2$ (orthogonal pair)", V("M098")],
       ["Next eigenvalue pair", "4.298"], ["Critical load $P_{cr} = \\lambda_1 N$ [kN]", V("M099")],
       ["Dominant mode", "global guided-column sway, $\\cos(\\pi z/L)$"], ["First-yield load factor (LC2)", V("M096")], ["Conventional inelastic (Johnson) estimate", "1.058"]],
      "Source: %s rows M091, M096, M098--M100, M107; \\texttt{BUCKLING\\_RESULTS.md}. $\\lambda_1$ is an idealised linear stability indicator, not a collapse load "
      "and not a factor of safety." % MD, size="\\footnotesize")

# ------------------------------------------------------------------------------------------------ Chapter 14
table("tab_support", "Support sensitivity at the baseline design (listed in order of definition, not ranked)", "tab:support", "lrrrl>{%s}p{0.20\\linewidth}" % L,
      ["Scenario", "Max VM [MPa]", "$\\lambda_1$", "$P_{cr}$ [kN]", "Mode", "Mechanism first reached"],
      [["S1 guided ($K$ = 1)", V("M090"), V("M098"), V("M099"), "guided sway", "elastic bifurcation (1.108 $<$ 1.730)"],
       ["S2 clamped--clamped ($K$ = 0.5)", V("M108"), V("M101"), g(V("M102")), "clamped column", "first yield (1.730 $<$ 4.300)"],
       ["S3 clamped--pinned ($K$ = 0.699)", V("M109"), V("M104"), g(V("M105")), "fixed--pinned", "first yield (1.730 $<$ 2.232)"]],
      "Source: %s rows M090, M098--M110. End reaction 548,936.6~N and mean axial stress $-$582.44~MPa in all three scenarios. "
      "The mechanism column compares $\\lambda_1$ with the first-yield factor of the idealised model only." % MD, size="\\footnotesize")

# ------------------------------------------------------------------------------------------------ Chapter 15
CASES = [("V01", "V01_LOW", "$V$ = 21.15 m/s"), ("V03", "V03_HIGH", "$V$ = 25.85 m/s"), ("Q01", "Q01_LOW", "$q''$ = 7200 W/m$^2$"),
         ("Q03", "Q03_HIGH", "$q''$ = 8800 W/m$^2$"), ("T01", "T01_THIN", "$t$ = 8 mm"), ("T03", "T03_THICK", "$t$ = 12 mm")]
BASEID = {"dp": "M036", "tout": "M037", "tmax": "M039", "lc1d": "M084", "lc1vm": "M086", "lc2vm": "M090", "lam": "M098", "pcr": "M099", "util": "M095"}
OFF = {"dp": 0, "tout": 1, "tmax": 2, "lc1d": 3, "lc1vm": 4, "lc2vm": 5, "util": 6, "lam": 7, "pcr": 8}
FIRST = {"V01_LOW": 125, "V03_HIGH": 134, "Q01_LOW": 143, "Q03_HIGH": 152, "T01_THIN": 161, "T03_THICK": 170}


def PV(case, q):
    return V("M%03d" % (FIRST[case] + OFF[q])) if case != "P00" else V(BASEID[q])


table("tab_pmatrix", "Parametric case matrix (one factor at a time around P00; S1 supports)", "tab:pmatrix", "lll>{%s}p{0.38\\linewidth}" % L,
      ["Case", "Variable", "Value (change)", "Held constant / mesh"],
      [["P00", "--", "baseline", "159,840 CFD cells; mesh B"], ["V01 / V03", "inlet velocity", "21.15 / 25.85 m/s ($\\mp$10\\,\\%)", "$q''$, geometry; P00 meshes"],
       ["Q01 / Q03", "outer-wall heat flux", "7200 / 8800 W/m$^2$ ($\\mp$10\\,\\%)", "$V$, geometry; P00 meshes"],
       ["T01 / T03", "wall thickness", "8 / 12 mm ($\\mp$20\\,\\%; $D_o$ 36 / 44 mm)",
        "total heat input $Q$ held ($q''$ = 8888.9 / 7272.7 W/m$^2$); new CFD meshes 155,520 / 168,480 cells, FE meshes 89,424 / 127,080 nodes"]],
      "Source: \\texttt{PROJECT\\_STATE.md} \\S17--\\S19. Range limits: the 600~K air property table (low $V$, high $q''$) and the 128,000-node licence (thick wall).", size="\\footnotesize")

rows = [["P00"] + [PV("P00", q) for q in ("dp", "tout", "tmax")] + ["602.76", "29,958", "555.27", "525.48"]]
EXTRA = {"V01_LOW": ("602.76", "26,962", "580.38", "546.96"), "V03_HIGH": ("602.76", "32,954", "534.61", "507.78"), "Q01_LOW": ("542.48", "29,958", "527.65", "501.07"),
         "Q03_HIGH": ("663.03", "29,958", "583.35", "550.31"), "T01_THIN": ("602.76", "29,958", "555.76", "524.54"), "T03_THICK": ("602.76", "29,958", "554.78", "526.38")}
for s, c, lab in CASES:
    rows.append([s] + [PV(c, q) for q in ("dp", "tout", "tmax")] + list(EXTRA[c]))
table("tab_pcfd", "Parametric CFD results (actual Fluent solutions, 9B-1)", "tab:pcfd", "lrrrrrrr",
      ["Case", "$\\Delta p$ [Pa]", "$T_{out}$ [K]", "$T_{max}$ [K]", "$Q$ [W]", "$Re_{in}$", "$T_{int,max}$ [K]", "$\\bar T_s$ [K]"], rows,
      "Source: %s ($\\Delta p$, $T_{out}$, $T_{max}$: VERIFIED); $Q$, $Re_{in}$, interface maximum $T_{int,max}$ and solid mean $\\bar T_s$ from "
      "\\texttt{10\\_Parametric\\_Study/CFD\\_Results/PARAMETRIC\\_CFD\\_TABLE.md} and \\texttt{PROJECT\\_STATE.md} \\S18.3." % MD, size="\\footnotesize")

rows = []
for s, c in [("P00", "P00_BASELINE")] + [(a, b) for a, b, _ in CASES]:
    p = P[c]
    base = "P00" if s == "P00" else c
    rows.append([s, PV(base, "lc1d"), "%.4f" % float(p["Axial growth [mm]"]), PV(base, "lc1vm"), PV(base, "lc2vm"), neg("%.3f" % float(p["LC2 mean axial stress [MPa]"])),
                 p["Critical temperature [K]"], p["Yield strength [MPa]"], PV(base, "util")])
table("tab_pstruct", "Parametric static structural results (actual Mechanical solutions, 9B-2; S1 supports)", "tab:pstruct", "lrrrrrrrr",
      ["Case", "LC1 def.\\ [mm]", "$\\Delta L$ [mm]", "LC1 VM [MPa]", "LC2 VM [MPa]", "$\\bar\\sigma_z$ [MPa]", "$T_{crit}$ [K]", "$S_y(T)$ [MPa]", "Util."], rows,
      "Source: %s (LC1 deformation, LC1/LC2 von Mises, utilisation: VERIFIED); $\\Delta L$, mean axial stress $\\bar\\sigma_z$, critical temperature and "
      "local $S_y$ from \\texttt{10\\_Parametric\\_Study/Results/PARAMETRIC\\_STRUCTURAL\\_RESULTS.csv}." % MD, size="\\footnotesize")

END = {"P00": "548.94", "V01": "602.29", "V03": "505.03", "Q01": "488.42", "Q03": "610.57", "T01": "408.19", "T03": "705.43"}
FYF = {"P00": "1.730", "V01": "1.575", "V03": "1.882", "Q01": "1.950", "Q03": "1.551", "T01": "1.741", "T03": "1.720"}
rows = []
for s, c in [("P00", "P00")] + [(a, b) for a, b, _ in CASES]:
    lam = PV(c, "lam")
    rows.append([s, END[s], lam, PV(c, "pcr"), FYF[s], "buckling" if float(lam) < float(FYF[s]) else "yield",
                 "\\textbf{$<$ 1: pre-buckling equilibrium}" if float(lam) < 1 else ("0.31\\,\\% above 1" if s == "V01" else "")])
table("tab_pbk", "Parametric linear buckling results under S1 (actual eigenvalue solutions, 9B-2)", "tab:pbk", "lrrrrll",
      ["Case", "$N$ [kN]", "$\\lambda_1$", "$P_{cr}$ [kN]", "First-yield factor", "First reached", "Note"], rows,
      "Source: %s ($\\lambda_1$, $P_{cr}$: VERIFIED); end force $N$ and first-yield factor from \\texttt{PROJECT\\_STATE.md} \\S19.3. Mode 1 is the global "
      "guided-sway shape in every case. For Q03 and T01 the LC2 static stresses are idealised pre-buckling equilibrium results: the linear stability "
      "criterion indicates loss of stability before the applied load level." % MD, size="\\footnotesize")

table("tab_psens", "Normalised sensitivities $S = (\\Delta y/y_0)/(\\Delta x/x_0)$ from the one-factor steps", "tab:psens", "lrrr",
      ["Response $y$", "Velocity $V$", "Heat flux $q''$", "Thickness $t$"],
      [["Pressure drop $\\Delta p$", "+1.367", "+0.421", "$\\approx 0$"], ["Maximum solid temperature", "$-$0.403", "+0.504", "+0.005"],
       ["LC1 axial growth", "$-$0.950", "+1.192", "+0.022"], ["LC2 max von Mises", "$-$0.871", "+1.111", "+0.022"],
       ["LC2 end reaction", "$-$0.886", "+1.113", "+1.354"], ["$\\lambda_1$", "+0.938", "$-$1.202", "+0.772"], ["$P_{cr}$", "+0.061", "$-$0.077", "+2.146"]],
      "Source: \\texttt{10\\_Parametric\\_Study/Results/PARAMETRIC\\_TRENDS.md} (central differences over the low/high cases). Families are compared only through $S$, "
      "because the step sizes differ ($\\pm$10\\,\\% for $V$ and $q''$, $\\pm$20\\,\\% for $t$).", size="\\footnotesize")

# ------------------------------------------------------------------------------------------------ Chapter 16
table("tab_unc", "Uncertainty register: nine separate sources (no combined percentage is formed)", "tab:unc",
      "l>{%s}p{0.20\\linewidth}>{%s}p{0.50\\linewidth}>{%s}p{0.11\\linewidth}" % (L, L, L), ["\\#", "Source", "Size / evidence", "Class"],
      [["7", "End-restraint definition", "$\\lambda_1$ = 1.108 / 2.232 / 4.300 (S1 / S3 / S2) at identical static stress: factor 3.9; mechanism switches", "primary"],
       ["8", "Geometric imperfection", "not modelled; reduces real capacity below $\\lambda_1$ by an unknown amount", "primary"],
       ["9", "Inelastic buckling", "intermediate columns ($KL/r$ 49.7--58.3 $<$ $C_c \\approx$ 60); Johnson estimate 1.058 for S1", "primary"],
       ["2", "CFD model form", "not quantified; 19.1 K CFD--analytical gap on $T_{max}$; $\\approx$30 K on the mean rise; $\\lambda_1 \\approx$ 0.98 on the Section 2 temperature basis", "secondary"],
       ["1", "CFD mesh", "$T_{max}$ $-$5.1 / +1.6 K; LC2 stress $-$10.1 / +2.8 MPa; $\\lambda_1$ +1.8 / $-$0.5\\,\\%", "secondary"],
       ["5", "Material data", "about $\\pm$2\\,\\% on $E$ and $\\alpha$; $S_y$ typical values", "secondary"],
       ["3", "Temperature mapping", "$\\le$ 0.081 K interior; LC1 inlet peak bound $\\pm$9.8 MPa", "smaller"],
       ["4", "Structural mesh", "LC2 peak $\\le 4.9\\times10^{-4}$, $\\lambda_1 \\le 5.4\\times10^{-5}$; LC1 bore $-$2.1\\,\\%", "smaller"],
       ["6", "Poisson's ratio", "about 1.4\\,\\% on LC1; none on LC2", "smaller"]],
      "Source: \\texttt{11\\_Final\\_Audit/MASTER\\_UNCERTAINTIES.md}. Sources are of different kind and sign (discretisation, model form, data scatter, assumption); "
      "a root-sum-square or linear sum would have no mathematical basis.", size="\\footnotesize")

# ------------------------------------------------------------------------------------------------ Appendices
table("tab_appA", "Complete input set of the baseline P00", "tab:appA", ">{%s}p{0.34\\linewidth}>{%s}p{0.56\\linewidth}" % (L, L), ["Input", "Value and basis"],
      [["Geometry", "$D_i$ 20 / $D_o$ 40 / $t$ 10 / $L$ 600 mm (D-008)"], ["Fluid", "air, incompressible ideal gas; property tables 250--600 K (D-009, D-021)"],
       ["Operating point", "300 K, 23.5 m/s, 0 Pa gauge at 101,325 Pa"], ["Thermal boundary", "8000 W/m$^2$ uniform on the outer wall; adiabatic end faces (D-015)"],
       ["Solid", "Inconel 718; $\\rho$ 8190 kg/m$^3$; $k(T)$, $c_p(T)$, $E(T)$, secant $\\alpha(T)$, $S_y(T)$ (D-010, D-026, D-036)"],
       ["Structural reference temperature", "300 K (D-041)"], ["Supports", "LC1 three-node determinate; LC2 = S1 (D-042, D-043)"],
       ["CFD mesh", "medium, 159,840 cells (D-034)"], ["Structural mesh", "B, 108,252 nodes / 23,400 SOLID186 (D-040, D-056)"],
       ["Parametric ranges", "$V$ $\\pm$10\\,\\%, $q''$ $\\pm$10\\,\\%, $t$ 8 / 12 mm with $Q$ held (D-058, D-060)"]],
      "Source: \\texttt{MASTER\\_ASSUMPTIONS.md} \\S2; decision numbers refer to \\texttt{PROJECT\\_STATE.md}. All inputs are selected (class B) with a stated rationale.",
      size="\\footnotesize")

table("tab_appB", "Section 2 analytical baseline (ANALYTICAL level, 1-D correlations; not a CFD or FE result)", "tab:appB", "lrl",
      ["Quantity", "Value", "Unit"],
      [["Mass flow rate", "8.686", "g/s"], ["Reynolds number inlet / outlet", "29,957 / 25,548", "--"], ["Mean Darcy friction factor (Petukhov)", "0.02413", "--"],
       ["$\\Delta p$ friction / acceleration / entry", "263.2 / 149.1 / 29.2", "Pa"], ["$\\Delta p$ CFD-comparable", V("M073"), "Pa"],
       ["Heat input $Q$", V("M071"), "W"], ["Outlet bulk temperature", V("M072"), "K"], ["$Nu$ exit: Dittus--Boelter / Gnielinski / corrected", "66.79 / 61.87 / 49.58", "--"],
       ["$h$ exit, corrected", "77.83", "W/(m$^2$\\,K)"], ["Inner / outer wall temperature, exit", "574.43 / " + V("M074"), "K"],
       ["Through-wall $\\Delta T$ (exit)", V("M075"), "K"], ["$R_{cond}/R_{conv}$", "0.0342", "--"], ["Mean solid temperature (length-averaged mid-wall)", "554.74", "K"],
       ["Free axial growth", V("M076"), "mm"], ["LC1 peak von Mises (Timoshenko)", V("M077"), "MPa"], ["LC2 axial stress $-E\\alpha\\Delta T$", neg(V("M078")), "MPa"],
       ["$S_y$ at 281.6\\,\\textdegree C / LC2 utilisation", V("M079") + " / " + V("M080"), "MPa / --"], ["LC2 / LC1 ratio", "40.3", "--"],
       ["Richardson / Brinkman number", "$4.37\\times10^{-5}$ / $1.82\\times10^{-3}$", "--"]],
      "Source: \\texttt{02\\_Engineering\\_Calculations/baseline\\_results.csv}; %s rows M071--M080." % MD, size="\\footnotesize")

table("tab_appE", "Additional structural results of the baseline", "tab:appE", ">{%s}p{0.55\\linewidth}r" % L, ["Quantity", "Value"],
      [["LC1 reaction resultant [N]", sci(V("M088"))], ["LC2 end reactions balanced to [N]", "$1.8\\times10^{-8}$"],
       ["LC2 reaction vs analytical restrained force of the same field", "agreement to $10^{-5}$"], ["LC2 interior von Mises [MPa]", "587--591"],
       ["LC2 axial stress at mid-span, outer / bore [MPa]", "$-$593.4 / $-$564.9"], ["LC2 maximum radial displacement [mm]", "0.0897"],
       ["LC1 free growth vs independent $\\int\\varepsilon_{th}\\,dz$", "agreement to $1.3\\times10^{-5}$"], ["LC2P peak von Mises [MPa]", "605.160918"],
       ["LC2 peak von Mises [MPa] (same precision)", "605.160873"], ["Energy-norm error LC1 / LC2", "0.70\\,\\% / 0.012\\,\\%"]],
      "Source: \\texttt{08\\_Structural\\_Analysis/STRUCTURAL\\_RESULTS.md}, \\texttt{PROJECT\\_STATE.md} \\S14.1, \\texttt{FINAL\\_ENGINEERING\\_AUDIT.md} \\S10.", size="\\footnotesize")

table("tab_appF", "First eigenvalue on every structural mesh (S1 supports)", "tab:appF", "lrr", ["Mesh", "Nodes", "$\\lambda_1$ (7 digits)"],
      [["XC", "24,171", "1.1079876"], ["C", "50,652", "1.1080342"], ["B (baseline)", "108,252", "1.1080471"], ["FR", "127,080", "1.1080404"],
       ["FA", "126,468", "1.1080483"], ["FC", "126,294", "1.1080410"]],
      "Source: \\texttt{PROJECT\\_STATE.md} \\S16.1 and \\texttt{BUCKLING\\_MESH\\_COMPARISON.md}. Family monotonic (apparent order 4.9, GCI $5.6\\times10^{-6}$); "
      "fine meshes within $6\\times10^{-6}$ of B; $P_{cr}$ = 608.22--608.25 kN on all meshes.", size="\\footnotesize")

with open(os.path.join(OUT, "tables_index.tsv"), "w", encoding="utf-8") as fh:
    for n, l, c in TABLES:
        fh.write("%s\t%s\t%s\n" % (n, l, c))
print("tables written:", len(TABLES))
